services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
      args:
        UID: 1000
        GID: 1000
    container_name: api-users-app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    user: "1000:1000"
    volumes:
      - ./app:/var/www/html
    networks:
      - api-users-network

  nginx:
    image: nginx:1.25
    container_name: api-users-nginx
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./app/public:/var/www/html/public
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - api-users-network

  db:
    image: mysql:8.0
    container_name: api-users-db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: api_users_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8100:3306"
    command: >
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-time-zone=+00:00
    networks:
      - api-users-network

volumes:
  db_data:
    driver: local

networks:
  api-users-network:
    driver: bridge